[package]
name = "chat"
version = "0.1.0"
authors = ["soupersauce <soupersauce@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.5"
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
byteorder = "1"

[frame]
name = "frame"
path = "src/frame.rs"
